name: Continuous Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  id-token: write

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      # Etapa 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Etapa 2: Configuración del JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Etapa 3: Construcción del proyecto con Maven
      - name: Build with Maven
        run: mvn clean install package

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: checkout-and-build
    steps:
      # Etapa 4: Configuración de AWS y ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Etapa 5: Construcción y empuje de la imagen Docker
      - name: Build Docker image
        run: docker build -t api-utec-customer-microservice:latest .

      - name: Tag Docker image
        run: docker tag api-utec-customer-microservice:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/api-utec-customer-microservice:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/api-utec-customer-microservice:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      # Etapa 6: Despliegue en Kubernetes
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl rollout status deployment/api-utec-customer-microservice
